apiVersion: 1
contactPoints:
  - orgId: 1
    name: webhook-app
    receivers:
      - uid: webhook-app
        type: webhook
        settings:
          url: http://webhook-app.webhook-app.svc:8080/alerts
          httpMethod: POST
