{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"name":"server","namespace":{{ .Release.Namespace | toJson }}},"automountServiceAccountToken":true}
---
{"apiVersion":"v1","kind":"ServiceAccount","metadata":{"name":"worker","namespace":{{ .Release.Namespace | toJson }}}}
---
{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"server","namespace":{{ .Release.Namespace | toJson }}},"rules":[{"apiGroups":["batch"],"resources":["jobs"],"verbs":["create","get","list","watch","delete"]},{"apiGroups":[""],"resources":["pods"],"verbs":["get","list","watch"]}]}
---
{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"name":"server","namespace":{{ .Release.Namespace | toJson }}},"subjects":[{"kind":"ServiceAccount","name":"server","namespace":{{ .Release.Namespace | toJson }}}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"server"}}
