import { randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { chmod, lstat, mkdir, open } from "node:fs/promises";
import { join } from "node:path";
import { ExecutionError } from "../execution/types.js";
import { operation } from "../lib/operation.js";
import type { Logger } from "../logger.js";

// Reject replaced or non-directory storage roots and restore the intended permissions.
async function directory(path: string, mode: number): Promise<void> {
  await mkdir(path, { recursive: true, mode });
  if (!(await lstat(path)).isDirectory())
    throw new ExecutionError("infrastructure");
  await chmod(path, mode);
}
// Seed a fresh synthetic canary at startup, without logging the generated bytes.
export async function initializeStorage(
  root: string,
  logger: Logger,
): Promise<void> {
  await operation(
    logger,
    "Create storage directories",
    { root, privateMode: "0700", runsMode: "0755" },
    async () => {
      await directory(root, 0o755);
      await directory(join(root, "private"), 0o700);
      await directory(join(root, "runs"), 0o755);
    },
  );
  await operation(
    logger,
    "Seed synthetic private data",
    { root, fileMode: "0600" },
    async () => {
      const path = join(root, "private", "pii.json");
      // Refuse substituted canary paths and validate the opened inode before writing.
      const handle = await open(
        path,
        constants.O_CREAT |
          constants.O_WRONLY |
          constants.O_NOFOLLOW |
          constants.O_NONBLOCK,
        0o600,
      );
      try {
        if (!(await handle.stat()).isFile())
          throw new ExecutionError("infrastructure");
        await handle.chmod(0o600);
        await handle.truncate(0);
        await handle.writeFile(
          JSON.stringify({
            synthetic: true,
            canary: `FAKE-PII-${randomUUID()}`,
            name: "Synthetic Person",
            email: "synthetic.person@example.invalid",
          }),
        );
      } finally {
        await handle.close();
      }
    },
  );
}
