apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app.kubernetes.io/name: demo-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: demo-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
