kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gvisor-code-execution
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.96.0.0/16
  ipFamily: ipv4
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1@sha256:14ffd6ee8a3daa20cc934ba786626b181e1797268c5465f2c299a7cf54494c77
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        podPidsLimit: 128
        containerLogMaxSize: 1Mi
        containerLogMaxFiles: 2
containerdConfigPatches:
  - |
    [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runsc]
      runtime_type = "io.containerd.runsc.v1"
    [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runsc.options]
      TypeUrl = "io.containerd.runsc.v1.options"
      ConfigPath = "/etc/containerd/runsc.toml"
