apiVersion: v1
kind: Namespace
metadata:
  name: executor
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.33
---
apiVersion: v1
kind: Namespace
metadata:
  name: executor-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: executor
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: executor-app
