apiVersion: v1
kind: ResourceQuota
metadata:
  name: executor-budget
  namespace: executor
spec:
  hard:
    pods: '2'
    count/jobs.batch: '2'
    requests.cpu: '1'
    limits.cpu: '1'
    requests.memory: 256Mi
    limits.memory: 256Mi
    requests.ephemeral-storage: 64Mi
    limits.ephemeral-storage: 64Mi
    persistentvolumeclaims: '0'
    secrets: '0'
    configmaps: '0'
