apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: execution-orchestrator
  namespace: executor
rules:
- apiGroups: [batch]
  resources: [jobs]
  verbs: [create, get, list, watch, delete]
- apiGroups: ['']
  resources: [pods]
  verbs: [get, list, watch]
- apiGroups: ['']
  resources: [pods/log]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: execution-orchestrator
  namespace: executor
subjects:
- kind: ServiceAccount
  name: backend
  namespace: executor-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: execution-orchestrator
