apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code-sandbox
resources:
  - namespace.yaml
  - postgres.yaml
  - sandbox.yaml
  - sandbox-networkpolicy.yaml
  - server.yaml
  - web.yaml
